### ISSUE TITLE
[ERROR] Task Contig01634:ErrorCounter Failed (__exit__)

### ISSUE THREAD

**Issue by zzlyk** [uio-cees/hpc#2]
2018-03-15 17:29:20,968 [INFO] Starting Contig01634:ErrorCounter
2018-03-15 17:29:20,984 [INFO] 124 reads to parse in Contig01634
2018-03-15 17:29:20,989 [INFO] 5% complete
2018-03-15 17:29:20,994 [INFO] 10% complete
2018-03-15 17:29:20,999 [INFO] 15% complete
2018-03-15 17:29:21,005 [INFO] 23% complete
2018-03-15 17:29:21,005 [INFO] 25% complete
2018-03-15 17:29:21,014 [INFO] 30% complete
2018-03-15 17:29:21,018 [INFO] 37% complete
2018-03-15 17:29:21,021 [INFO] 44% complete
2018-03-15 17:29:21,024 [INFO] 48% complete
2018-03-15 17:29:21,025 [INFO] 50% complete
2018-03-15 17:29:21,028 [INFO] 56% complete
2018-03-15 17:29:21,029 [INFO] 60% complete
2018-03-15 17:29:21,036 [INFO] 65% complete
2018-03-15 17:29:21,044 [INFO] 70% complete
2018-03-15 17:29:21,050 [INFO] 75% complete
2018-03-15 17:29:21,052 [INFO] 81% complete
2018-03-15 17:29:21,053 [INFO] 85% complete
2018-03-15 17:29:21,055 [INFO] 94% complete
2018-03-15 17:29:21,056 [INFO] 96% complete
2018-03-15 17:29:21,056 [ERROR] Exception raised in task Contig01634:ErrorCounter - __exit__
2018-03-15 17:29:21,056 [ERROR] Dumping Traceback:
Traceback (most recent call last):
  File "/share/nas1/xiek/pipeline/svn/SVcalling/nextsv/aligners_and_callers/PBSuite_15.8.24/pbsuite/honey/HSpots.py", line 500, in run
    next_task(self.bam, self.reference, self.honH5)
  File "/share/nas1/xiek/pipeline/svn/SVcalling/nextsv/aligners_and_callers/PBSuite_15.8.24/pbsuite/honey/HSpots.py", line 597, in __call__
    with honH5.acquireH5('a') as h5dat:
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/share/nas1/xiek/pipeline/svn/SVcalling/nextsv/aligners_and_callers/PBSuite_15.8.24/pbsuite/honey/HSpots.py", line 439, in acquireH5
    with self.__lock:
AttributeError: __exit__
2018-03-15 17:29:21,059 [ERROR] Task Contig01634:ErrorCounter Failed (__exit__)
2018-03-15 17:29:21,059 [INFO] Finished
2018-03-15 17:29:21,059 [INFO] Thread Consumer-1: Exiting

i don't why this happened. thanks all

**Comment by lexnederbragt** [comment]
I am afraid this is not the right place to ask this question. I advice you to find a forum or mailing list where users of PBSuite can ask for help.
